bf16: true
cutoff_len: 1024
dataset: bfcl_single_gpt,xlam_gpt_cot,alpaca_gpt4_data
dataset_dir: /root/autodl-tmp/data
ddp_timeout: 180000000
do_train: true
enable_thinking: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /root/autodl-tmp/qwen3-4b-think-local
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/Qwen3-4B-Thinking-2507/lora/train_2026-01-07-23-25-37
packing: false
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
swanlab_api_key: OZ97g61zaacKERkh3vL8P
swanlab_mode: cloud
swanlab_project: llamafactory
swanlab_run_name: qwen3-4b-think-v2
template: qwen3
trust_remote_code: true
use_swanlab: true
val_size: 0.1
warmup_steps: 0
